Add Slack Notification step

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,13 +12,14 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        ruby: ['3.0', '3.2', head, jruby-head]
+        # ruby: ['3.0', '3.2', head, jruby-head]
+        ruby: ['3.0', '3.2', head]
         operating-system: [ubuntu-latest]
-        include:
-          - ruby: '3.0'
-            operating-system: windows-latest
-          - ruby: jruby-head
-            operating-system: windows-latest
+        # include:
+        #   - ruby: '3.0'
+        #     operating-system: windows-latest
+        #   - ruby: jruby-head
+        #     operating-system: windows-latest
 
     name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}
     runs-on: ${{ matrix.operating-system }}
@@ -36,16 +37,38 @@ jobs:
       - name: Run rake
         run: bundle exec rake
 
+      - name: Fail if building with Ruby 3.0
+        if: matrix.ruby == '3.0'
+        run: exit 1
+        
+      # - name: Slack Failure Notification
+      #   uses: 8398a7/action-slack@v3
+      #   with:
+      #     status: ${{ job.status }}
+      #     author_name: Build
+      #     fields: all
+      #     mention: here
+      #     if_mention: 'failure, cancelled'
+      #   env:
+      #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
+      #   if: failure() # Pick up events even if the job fails or is canceled.
+
       - name: Slack Failure Notification
         uses: 8398a7/action-slack@v3
         with:
           status: ${{ job.status }}
-          author_name: Build
-          fields: all
-          mention: here
-          if_mention: 'failure, cancelled'
+          fields: workflow,job,commit,repo,ref,author,took
+          custom_payload: |
+            {
+              attachments: [
+                {
+                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
+                  text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
+                }
+              ]
+            }
         env:
-            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
         if: failure() # Pick up events even if the job fails or is canceled.
 
   coverage:
